<?php
/**
 * Main file
 * 
 * Contains a View class that displays the web app *
 */

namespace View;

require_once './Classes/View/SmartyConfiguration.php';

/**
 * View Main Class extends SmartyConfiguration.
 * 
 * Has the methods to handle the HTTP requests generated by the web application.
 */
class Main extends \View\SmartyConfiguration
{
	/**
	 * Constructor extends SmartyConfiguration
	 */
	public function __construct()
	{
		parent::__construct();
	}
	
	/**
	 * Gets data from HTTP methods.
	 * 
	 * Gets data from HTTP (GET or POST), searching in the php $_REQUEST array.
	 * 
	 * @param string|int $key 
	 * 
	 * @return mixed False if no data were found.
	 */
	public function get($key)
	{
		if (isset($_REQUEST[$key]))
			return $_REQUEST[$key];
		else
			return false;		
	}
	
	/**
	 * Gets file data.
	 * 
	 * function for insert a new resource
	 * 
	 * @param string|int $key
	 * @return mixed
	 */
	public function getFile($key)
	{
		return $_FILES[$key];
	}
		
}
?>